[package]
name = "kdash"
version = "0.1.0"
authors = ["deepu105 <d4udts@gmail.com>"]
description = """
A fast and simple dashboard for Kubernetes
"""
documentation = "TODO"
keywords = ["kdash", "kubernetes", "dashboard"]
repository = "https://github.com/deepu105/kdash"
readme = "README.md"
license = "MIT"
exclude = ["assets/*", ".github", "Makefile.toml", "CONTRIBUTING.md", "*.log", "tags"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]

[dependencies]
crossterm = "0.19"
tui = { version = "0.14", default-features = false, features = ['crossterm'] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
clap = "2.33.3"
tokio = { version = "1.0", features = ["full"] }
rand = "0.8"
duct = "0.13"
anyhow = "1.0.38"
backtrace = "0.3.56"
regex = "1"
# Add openssl-sys as a direct dependency so it can be cross compiled using the "vendored" feature below
openssl-sys = "*"
kube = "0.52"
kube-runtime = "0.52"
k8s-openapi = { version = "0.11", default-features = false, features = ["v1_20"] }

[features]
# Force openssl-sys to statically link in the openssl library. Necessary when
# cross compiling.
vendored = ["openssl-sys/vendored"]

[[bin]]
bench = false
path = "src/main.rs"
name = "kdash"