name: kdash-temp
base: core18
adopt-info: kdash
summary: KDash
description: |
  A fast and simple dashboard for Kubernetes

grade: stable
confinement: strict

parts:
  kdash:
    plugin: rust
    source: .
    build-packages:
      - libssl-dev
      - pkg-config
      - libxcb1-dev
      - libxcb-render0-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
    stage-packages:
      - libxau6
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xfixes0
      - libxcb1
      - libxdmcp6
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0)"
      echo $last_committed_tag
      VERSION="$(git describe --first-parent --tags --always)"
      echo "Setting version to $VERSION"
      snapcraftctl set-version "${VERSION}"

apps:
  kdash-temp:
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH
    command: kdash
    plugs:
      - desktop
      - network
      - network-bind
