apiVersion: v1
items:
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    annotations:
      deprecated.daemonset.template.generation: "1"
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/8xUTW/jNhD9K8WcKUVaf8QW0MMim0PQrmPY3l4CIxhRo5g1RQrkSI1h6L8XlJ21s/kqtj306OHj8+N7o7eHrTIFZPAFqbJmSQwCsFZ/kPPKGsgA69pftCkIqIixQEbI9mCwIsjAt1LnETukUm1B9GNfowxn2yanyO88UwUCpCNkZc1KVeQZqxoy02gtQGNO2gdOm/9Jkj1x7JSNJTJripW92KDfQAblIB1ejtLRpzIvL5PxaFQMZJKOi8F4QtMkTSfTwaQcE4IIsqQ17KzW5OLtwJ+xGVuQJ02SrQusqD1BJwCNsdxLfFeMKg7PPvGDeBNs/zLkood2CxlctKn45Tdlil+X5Fol6cN7R49P7n4Mf837TkAPWFBJjowkD9nd/nnIfb7HTTjJeyGg6V8/pXwwyqdllJbpOBpigtG0vMwjORlRmabpZU6XIfGTQxm7hrp1J8DXJIO9pwT2UCHLze/f1wDr+sVmdZ0ApqrWyNRfOVvFf7BZr1G+vyW+lT+8vjtTH66hMuQOVh6ROo9q6ziaJCBAVfgQhg6N3JC72GpV1+QinWdtEn+KAyag32bYWM9z6xiySSJOf3ka1c6ylVZDBqurOXRrAWTac77l4up+frtYgYAWdRNGkwQ68R3w5Xq5up8vble3Z5Ce7EfMhyw387PzNImHgzidDON0nPTKHHnbuH759t3Rnnmj9dxqJXeQwU05szx35MmEDvIkG6d4d2UN0yP3rmONudKKFR1SLQrI7mB2vbr//OXrzQzWXXem6snM4XDwb/M4UJwCGQ4HLxLpZz8VSWD/DzJ5jeZ/EspaAFtN7qle7/awpcAfyjhyVlMcGssZYvLh86vQ86FZ63Crb+rrR+XZgwAqS5IMGczsUm6oaDT1D3+f8vipR7VGQz/FfOUUK4n6c1FY42+N3r1K061DVTR1gUxLdsj0sAvO8K4OKSys1so8fOvPQYB79ruvw8dvBltUGnNNkKVdXz2M3PQOy8Y5Mjxrqpzck8wCskSA6WdflffPxgV55ah4+8aCsNhBlnTd3wEAAP//kF8EoBAIAAA
      objectset.rio.cattle.io/id: svccontroller
      objectset.rio.cattle.io/owner-gvk: /v1, Kind=Service
      objectset.rio.cattle.io/owner-name: traefik
      objectset.rio.cattle.io/owner-namespace: kube-system
    creationTimestamp: "2021-07-05T09:36:45Z"
    generation: 1
    labels:
      objectset.rio.cattle.io/hash: f31475152fbf70655d3c016d368e90118938f6ea
      svccontroller.k3s.cattle.io/nodeselector: "false"
    managedFields: []
    name: svclb-traefik
    namespace: kube-system
    ownerReferences:
    - apiVersion: v1
      controller: true
      kind: Service
      name: traefik
      uid: 9eb35b9f-1f16-4a0a-9f7b-c85ef1117be7
    resourceVersion: "631"
    uid: ddce45fd-18ca-49fc-97d3-a8a5b7309f0c
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: svclb-traefik
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: svclb-traefik
          svccontroller.k3s.cattle.io/svcname: traefik
      spec:
        containers:
        - env:
          - name: SRC_PORT
            value: "80"
          - name: DEST_PROTO
            value: TCP
          - name: DEST_PORT
            value: "80"
          - name: DEST_IP
            value: 10.43.184.160
          image: rancher/klipper-lb:v0.2.0
          imagePullPolicy: IfNotPresent
          name: lb-port-80
          ports:
          - containerPort: 80
            hostPort: 80
            name: lb-port-80
            protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - env:
          - name: SRC_PORT
            value: "443"
          - name: DEST_PROTO
            value: TCP
          - name: DEST_PORT
            value: "443"
          - name: DEST_IP
            value: 10.43.184.160
          image: rancher/klipper-lb:v0.2.0
          imagePullPolicy: IfNotPresent
          name: lb-port-443
          ports:
          - containerPort: 443
            hostPort: 443
            name: lb-port-443
            protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
  status:
    currentNumberScheduled: 1
    desiredNumberScheduled: 1
    numberAvailable: 1
    numberMisscheduled: 0
    numberReady: 1
    observedGeneration: 1
    updatedNumberScheduled: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
