apiVersion: v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      annotations:
        operator-sdk/primary-resource: monitoring/kiali
        operator-sdk/primary-resource-type: Kiali.kiali.io
      creationTimestamp: "2022-06-27T16:33:06Z"
      labels:
        app: kiali
        app.kubernetes.io/instance: kiali
        app.kubernetes.io/name: kiali
        app.kubernetes.io/part-of: kiali
        app.kubernetes.io/version: v1.41.0
        version: v1.41.0
      name: kiali-viewer
      namespace: default
      resourceVersion: "102143312"
      uid: 78ce4200-d457-44e7-b6a2-9602ff6b44b7
      managedFields: []
    rules:
      - apiGroups:
          - ""
        resources:
          - configmaps
          - endpoints
          - pods/log
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - ""
        resources:
          - namespaces
          - pods
          - replicationcontrollers
          - services
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - ""
        resources:
          - pods/portforward
        verbs:
          - create
          - post
      - apiGroups:
          - extensions
          - apps
        resources:
          - daemonsets
          - deployments
          - replicasets
          - statefulsets
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - batch
        resources:
          - cronjobs
          - jobs
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - networking.istio.io
          - security.istio.io
        resources:
          - '*'
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - authentication.k8s.io
        resources:
          - tokenreviews
        verbs:
          - create
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
